### ISSUE TITLE
VFX preview functions

### ISSUE THREAD

**Issue by PrincessRTFM** [0ceal0t/Dalamud-VFXEditor#1]
Currently, there's no way to preview a VFX to make sure it's actually the one you're looking for, except to select it as the target to _be_ replaced. I'd like to be able to preview VFX both as the one to replace the target _with_, and better yet in the VFX selection dialog box.

**Comment by 0ceal0t** [comment]
added: https://github.com/0ceal0t/Dalamud-VFXEditor/commit/a15abab3ceb36f2a494a23b15841baf4ec394954
