### ISSUE TITLE
changing a vfx edit to a targetable ability?

### ISSUE THREAD

**Issue by heyleeboo** [0ceal0t/Dalamud-VFXEditor#10]
Hi! So I'm currently working on changing my ability into a non-player action in the game. For context, I want to change my Aflatus Misery ability on white mage to the Flood ability. My issue is that, while the animation works, it remains under me and I don't know how to make it into a targetable ability (so that it would be under my target) - or if that's even possible. Any help or a steer in the right direction would be greatly appreciated. ;_;

**Comment by 0ceal0t** [comment]
look in the "binders" tab. There should be a dropdown somewhere in there that you can change from "caster" to "target"

**Comment by heyleeboo** [comment]
I'm so dumb LOL- I found it, thank you.
