### ISSUE TITLE
Display error occurred while opening the vfx library

### ISSUE THREAD

**Issue by Gio1029** [0ceal0t/Dalamud-VFXEditor#105]
![ffxiv_20230410_143014_840](https://user-images.githubusercontent.com/122195599/230842871-2408a1bd-6934-4a26-9762-32eb073db7d3.png)
This happened when I open Library, and change back to normal after shrinking the library window.

Besides, when I want to creat a new value point in rotation under degrees, the point would be created incorrectly. For example, when I creat a 1.571° value point under degrees, the point will be created as 90°, which is the degrees corresponding to 1.571 in radians. And also, I cannot select the point under angle system.

**Comment by Gio1029** [comment]
[xllog.txt](https://github.com/0ceal0t/Dalamud-VFXEditor/files/11238973/xllog.txt)
This is the xllog of opening vfxeditor directly after I'm into the game. I only installed VFXedit, Easyeye and Penumbra, and I tried disabled the other two then open vfxeditor, this issue still exists. 
In the above screenshot you can see two sliders there. I found that when the slider of the library is pulled to the very bottom, it can return to normal, but once I slide up or open one content in the library, it will be error again. Seems like it only shows normal when the slider is at the very bottom.

**Comment by 0ceal0t** [comment]
oh, I found the issue. I'll have it fixed soon!
