### ISSUE TITLE
Unable to change the volume with the scd editor

### ISSUE THREAD

**Issue by reitatoli** [0ceal0t/Dalamud-VFXEditor#106]
When trying to change the bgm for limsa using an .ogg file and then using the converter in the audio tab but I'm unable to get a change in the volume. I've tried changing the volume in the sounds tab to 1.000, 5.000, 30.000, 100.00 and there isn't a change. I tested using the orchestration plugin and also changed instances and switched tracks several times before each test without any luck. I've included a zip of the ogg file I was using and the exported .scd I was using for the mod. I've also changed in
[scd export and original ogg file.zip](https://github.com/0ceal0t/Dalamud-VFXEditor/files/11217687/scd.export.and.original.ogg.file.zip)

**Comment by 0ceal0t** [comment]
iirc, setting the volume above 1 doesn't actually do anything. Did you try boosting the volume in a program like audacity, or checking to see if the volume isn't being reduced anywhere in the Sound/Tracks tabs?

**Comment by reitatoli** [comment]
after careful checking the volume is increasing when set to 1.00 compared to .380. Thank you again for the assistance.
