### ISSUE TITLE
Cannot create and select points correctly in rotation under degrees

### ISSUE THREAD

**Issue by Gio1029** [0ceal0t/Dalamud-VFXEditor#108]
Thanks for fixing the display error issue these days. And I also found that something wrong with the "Degrees" values when editing the rotation curves.
When I creat a new point in degrees, the point would be created in radians and then converted to degrees. For example, when I creat a 30° under degrees, the point will be created as 1718.873°, which is the degrees corresponding to "30" in radians.
Also, I cannot select the created point under degrees. I have to come back to radians, select the point, back to Degrees, click "Fit To Contents", and then I can see the point in the middle of the viewport. This is cumbersome and prevents me from creating normal curves under degrees. I hope this can be optimized. Thanks again!

**Comment by Gio1029** [comment]
Found new bug. When duplicate a particle, the duplicated one will lose texture and model settings. Though it looks still fine when spawn, but sometimes it takes a while then it become actually no model or texture when spawn.
On the contrary, when duplicate an emitter with an effector, although the duplicated one seems to have no effector, it actually still have and I must manually add an effector to it and then remove the effector to successful remove the effector from the duplicated one.

**Comment by 0ceal0t** [comment]
found the issue with both of those. will be fixed in the next update
