### ISSUE TITLE
[PARSING ISSUE]

### ISSUE THREAD

**Issue by KabrTL** [0ceal0t/Dalamud-VFXEditor#116]
What is the name or path of the file you are trying to open?
Its a Penumbra mod
D:\FFEXIV MODS\Animation (DRK) - Soldier First Class (2)\chara\human\c0101\animation\a0001\bt_2sw_emp\resident\move_a.pap

What type of file is it (VFX, TMB, PAP, etc.)?
PAP

**Comment by 0ceal0t** [comment]
should be fixed with latest update (1.7.4.7)
