### ISSUE TITLE
High probability of the game crashing when changing the "Target Emitter"

### ISSUE THREAD

**Issue by Gio1029** [0ceal0t/Dalamud-VFXEditor#123]
When selecting the "Target Emitter" for an emitter placed in "Create Emitter" of current emitter, the game randomly crashes. This happens quite often (about once in 3 times in my try) and no error box will pop up.
I tried to add a new blank in "Create Emitter" and then select the "Target Emitter" for it, or change the "Target Emitter" of an emitter which is already located in "Create Emitter", this issue still happend. I also tried modify multiple different vfx files, Including some of the game's original, this issue persists. So it doesn't appear to be a problem with the file I edited.

**Comment by 0ceal0t** [comment]
I wasn't able to reproduce this crash. Could you give me an exact step-by-step for how you triggered it (which file you used, what emitter you modified, what you set it to)?

**Comment by Gio1029** [comment]
I randomly open a vfx (Rubicante #0 this time) and then this happen:

https://github.com/0ceal0t/Dalamud-VFXEditor/assets/122195599/99d15465-2420-4830-934b-507acd1f6663

**Comment by 0ceal0t** [comment]
can you check your `/xllog`?

**Comment by 0ceal0t** [comment]
or, actually, since the game is crashing, your `dalamud.log` in `%appdata%\XIVLauncher\`

**Comment by 0ceal0t** [comment]
ok, I was able to reproduce it. I'll look into what's causing the issue

**Comment by 0ceal0t** [comment]
I think the issue is that you're basically making a cyclical emitter. For example, Emitter 5 is spawned from Emitter 1, so if you make 5 spawn 1, it would form a cycle.

Does this only happen under those circumstances? In the next update, I'll add checks to make sure that can't happen

**Comment by 0ceal0t** [comment]
![image](https://github.com/0ceal0t/Dalamud-VFXEditor/assets/18051158/17945b3a-bbad-4b68-b9ac-e22ca4c6ae6d)

**Comment by Gio1029** [comment]
That make sense, but I just thought nothing would happen if I didn't click UPDATE. It would be better if a check can be added to prevent game crashing due to wrong selection
