### ISSUE TITLE
Nothing happend after modified VFX of Sacred Soil & Asylum 

### ISSUE THREAD

**Issue by Lornvene** [0ceal0t/Dalamud-VFXEditor#128]
Seems only Sacred Soil and Asylum got this problem, Salted Earth works perfectly fine.
In Preview it worked, but in actual game it didn't. (I deleted all the "Particle (model)" )
![image](https://github.com/0ceal0t/Dalamud-VFXEditor/assets/41856088/7e371a0e-5fdd-4d6f-a36d-4a4d8420e1e6)
![image](https://github.com/0ceal0t/Dalamud-VFXEditor/assets/41856088/4b439732-791e-4ab3-990f-7f16831c273a)

**Comment by 0ceal0t** [comment]
With the update to asylum and soil's size, they were given new VFX paths (for example, asylum is now `vfx/common/eff/abi_cnj022g.avfx`). They haven't been updated yet in VFXEditor, so until then you'd need to find those paths manually
