### ISSUE TITLE
VFX Enemy to Player replacement; Audio not working?

### ISSUE THREAD

**Issue by torchick11** [0ceal0t/Dalamud-VFXEditor#14]
So when you preview enemy skills and even replace them, they don't seem to play the spell effect (IE fragor maximus), I tried this and it didn't replace holy's audio, holys audio still played. What do I do in this circumstance?

**Comment by 0ceal0t** [comment]
Some sound effects are played by the vfx, others are from the skills .tmb file.

If its the latter, your only real option is finding the tmb file and editing it manually, since I'm still working on adding tmb editing to vfxeditor

**Comment by torchick11** [comment]
So the TMB editor was added but I can't really find the audio files associated with some enemy spells?

**Comment by 0ceal0t** [comment]
if you're specifically talking about fragor maximum, it might be a sound played by the instance itself (as opposed to by an action). In which case, you'll have to do some digging manually to find it

**Comment by torchick11** [comment]
Its not just things like fragor maximus, spell-in-waiting also doesn't seem to carry a sound. I'd dig into the files if any of the hashes were updated on things like explorer.
