### ISSUE TITLE
QoL Commands

### ISSUE THREAD

**Issue by Ghoulfriend** [0ceal0t/Dalamud-VFXEditor#145]
Hi, 

Currently the only way to open the UI makes you go through VFX Editor window, where you pick further editors such as Tmb, Pap, Scd, etc. Could further commands be added for these? For example: /papedit would simply open to the pap editor skipping the previous window.
![image](https://github.com/0ceal0t/Dalamud-VFXEditor/assets/106831003/de13658b-f58f-4508-8911-4d16a9671b80)

**Comment by 0ceal0t** [comment]
It's not currently documented anywhere, but you can use `/vfxedit pap` , `/vfxedit tmb`, etc. to open the specific windows
