### ISSUE TITLE
Cannot open vfx editor with /vfxedit

### ISSUE THREAD

**Issue by oxxtazxxo** [0ceal0t/Dalamud-VFXEditor#149]
Basically the title.  Cannot open vfxedit using the /vfxedit command but can only open the editor FROM the plugin page (/xlplugins). no error shows up in /xllog

**Comment by oxxtazxxo** [comment]
Checked with other friends, its the same issue as well so it isnt a isolated event

**Comment by mkaminsky11** [comment]
I accidentally broke it with the latest update. For now you can use `/vfxedit vfx`, `/vfxedit pap` until it’s fixed

**Comment by 0ceal0t** [comment]
I accidentally broke it with the latest update. For now you can use `/vfxedit vfx`, `/vfxedit pap`, etc until it’s fixed

**Comment by 0ceal0t** [comment]
fixed in latest update
