### ISSUE TITLE
Weapon VFX Merging problem

### ISSUE THREAD

**Issue by Gols2445** [0ceal0t/Dalamud-VFXEditor#15]
Hello, I followed the instructions on how to merge vfx into one and it does show the merged effects of both weapons. But when I unsheathe the weapon, the added vfx from the merge persists for some reason. Is there something I'm missing or doing wrong here?

**Comment by 0ceal0t** [comment]
Weapons vfxs are a bit weird. The hiding while sheathing is controlled by the "Triggers" in the scheduler. The most straightforward way to fix this is probably to move all of the items from the timeline which you imported into the existing vfx timeline (you'll need to manually recreate them), and then once they're moved over, delete the imported timeline

**Comment by Gols2445** [comment]
I know you might have other important things to do, but may I trouble you with giving an example on how to do it?

**Comment by 0ceal0t** [comment]
sure. For this example, I'm going to put merge the effect of the _Ultimate Deneb_ onto that of the _Ultimate Dreadwyrm Torquetum_.

1. Open up the _Deneb_, go to timelines, and export timeline 0
![t1](https://user-images.githubusercontent.com/18051158/142250547-5c0a0056-693e-4d10-a8cd-a39336893d16.PNG)

2. Open the _Torquetum_ (make sure to select it as both the "source" and "preview" vfx), go to timelines, and import the one which we just exported from the _Deneb_
![t2](https://user-images.githubusercontent.com/18051158/142250776-8c6fcd23-e0d2-4f87-9275-f91acf06161b.PNG)

3. At this point the last timeline (in my case, timeline 4) is the one which we imported from the _Deneb_. The goal of the next few steps is to get all of the "Items" in timeline 4 into the "Items" of timeline 0
![t3](https://user-images.githubusercontent.com/18051158/142251120-6c652d17-6ec0-48ad-abfe-c1b971699da8.PNG)

4. In **timeline 0**, create a new item using the "+" icon, click on it, and fill it out exactly the same as the first item in timeline 4 (this means the binder select, emitter select, end time, etc.)
![t4](https://user-images.githubusercontent.com/18051158/142251371-7ed38c54-f4ea-4add-8c46-7fc985f5bc07.PNG)

5. Repeat step 4 (creating an item in timeline 0 and fill it out) for each item in timeline 4

6. Once you have effectively copied all of the items from timeline 4 into timeline 0, delete **timeline 4**
![t5](https://user-images.githubusercontent.com/18051158/142251605-93d970d9-572a-42dc-a378-70b5a6195afd.PNG)

7. Press "update," and you should be done

Let me know if you have any more questions

**Comment by Gols2445** [comment]
It worked as you said! Though I would request that you put this to the wiki guide if anyone else would come and try it as well. Thank you for your help!
