### ISSUE TITLE
AoE Targetting Issues

### ISSUE THREAD

**Issue by NaesKun** [0ceal0t/Dalamud-VFXEditor#16]
Heyo 0cel0t, is yo boi Naes.

Jokes aside, I'm having some issues trying to setup AoE target VFX for Monk Skills: Rockbreaker and Arm of the Destroyer. On VFXEditor both have a TMB path of: chara/action/normal_hit/normal_hit.tmb but I noticed there are no VFX files associated with these skills. 

I uninstalled all my previous VFX/Skill Swap mods to see if it would bring it back, but alas it did not.

With that being said I have a few questions:

1.) Can you double check your game to see if those files even exist? If they do, then I can probably just reinstall to get them back.
2.) If they're not there for you, they probably don't actually have VFX. With that being said, is there a way to adjust VFX bindings so that I consistently see the VFX hit effects on AoE targets. Currently, it goes off occasionally on 2 or more targets, often one target, and frequently none at all.
3.) Are there any plans in the pipeline for VFXEdit so that we can manually add our own VFX files to Skill / Targets?

Thanks a lot so far with your help 0cel0t, I've been making great strides in my modding thanks to this tool.

**Comment by 0ceal0t** [comment]
fixed with the latest update. For future reference, `normal_hit.tmb` is a generic hit effect shared by almost all skills. It doesn't have any VFXs

**Comment by NaesKun** [comment]
Hi 0ceal0t!

Super excited about the new update, it addresses a lot of my current issues. However, I was wondering if VFXEditor can simply adjust the Hit Tmb Path without actually replacing the TMB file. Is there a way to do this? I've explored the TMB tool and was unable to find the way to do this.

Would make it a lot easier to deal with annoying VFX's using only the generic hit effect.
