### ISSUE TITLE
Changing TMB Paths

### ISSUE THREAD

**Issue by NaesKun** [0ceal0t/Dalamud-VFXEditor#17]
Hi 0ceal0t!

Super excited about the new update, it addresses a lot of my current issues. However, I was wondering if VFXEditor can simply change the Hit Tmb Path of a specific skill without actually replacing the TMB file? Is there a way to do this? I've explored the TMB tool and was unable to find the way to do this.

Would make it a lot easier to deal with annoying VFX's using only the generic hit effect.

**Comment by 0ceal0t** [comment]
You can't change the tmb path with vfxeditor, no. The tmb path is determined by the xls sheets (you can see them using godbert https://github.com/xivapi/SaintCoinach/releases/tag/f2d06fc)

**Comment by NaesKun** [comment]
Hi 0cel0t,

Thanks for being quick with the responses. Can the xls sheet be adjusted through GodBert/SaintCoinach or is it a view only application?

**Comment by 0ceal0t** [comment]
I don't believe they have editing. It's technically possible to edit them (since they're basically excel files), but it would get kind of messy since you'd need to redo it everytime the game gets updated and new actions/timelines are added to the sheet

**Comment by NaesKun** [comment]
Closing issue, TMB path adjustment will require another program/plugin that adjusts the xls file every time we login.
