### ISSUE TITLE
Monster Size overrides Scale Setting for Particles

### ISSUE THREAD

**Issue by NaesKun** [0ceal0t/Dalamud-VFXEditor#19]
Some skills have it so that large size of monsters will cause the VFX to become as massive as the monster. Is there a way to turn off this automatic scaling or if there are specific things in VFX Editor that allows us to override this?

**Comment by 0ceal0t** [comment]
that sounds like a binder setting. Try messing with stuff in the "Binders" tab, maybe "VFX Scale" or "VFX Scale Bias"

**Comment by NaesKun** [comment]
VFX Scale is off and VFX Scale Bias doesn't seem to do anything when I enter different numbers. Adjusting the overall scale seems to affect the VFX, but I'm not sure why the particles won't reflect individual changes.

**Comment by 0ceal0t** [comment]
which vfx are you using? setting "VFX Scale" to "off" and "VFX Scale Bias" to zero removes the target scaling for me

**Comment by NaesKun** [comment]
Ahh there we go. I didn't understand how VFX Scale Bias worked since most skills are set to 1, so I assumed it should work normally like that. Thanks 0ceal0t, I'm completing this issue.
