### ISSUE TITLE
Texture import does not support PNG

### ISSUE THREAD

**Issue by Kompreya** [0ceal0t/Dalamud-VFXEditor#2]
When selecting a texture to import/replace, it shows PNG as a valid file type. However, upon selecting a PNG, file explorer closes and the texture is not replaced. Works with DDS, however.

Not sure if PNG is just not actually a supported file type, or if VFXEditor is failing to import a PNG.

Attempted this with ascd_s01ah.atex (as well as 02-08)

**Comment by 0ceal0t** [comment]
PNG support is spotty rn. I'll probably fix it up at some point, but you're better off just using DDS to be safe

**Comment by Kompreya** [comment]
Thank you! I suspected using DDS was best practice anyways.
