### ISSUE TITLE
About the warning in the guide

### ISSUE THREAD

**Issue by LucyWhiteheart** [0ceal0t/Dalamud-VFXEditor#23]
When you say don't modify dashes or jumps, does this apply to stuff like sprint or even just the normal running animation, I don't know if it's even possible to change them but I wanted to know before trying if they counted for your warning
I only found the run.tmb so far anyway

**Comment by 0ceal0t** [comment]
No, I meant things like gap closers. Sprinting and running should be ok

**Comment by LucyWhiteheart** [comment]
Alright thank you for your time. I'll close the issue after a bit but if you have any idea on how I could find the animation for the basic running of a specific race, I would greatly appreciate it as the only thing I found is the .tmb (i'm sure of it because it has the right ID) but I can't seem to be able to edit anything about it .

**Comment by LucyWhiteheart** [comment]
I ended up finding it but I guess the reason why it's not possible is bc the pap has multiple animations in it and currently there is no way to mod a single anim in a pap with more than 1 ?

**Comment by 0ceal0t** [comment]
it's possible, you'll just need to manually copy the havok animation similar to this: https://github.com/0ceal0t/Dalamud-VFXEditor/wiki/Example:-Replacing-Fire-animation-with-Fell-Cleave

**Comment by 0ceal0t** [comment]
basically, modify the existing pap file rather than replacing it altogether

**Comment by LucyWhiteheart** [comment]
Alright I'll try that thank you once more, although I'm a bit worried, it makes sense for abilities with forced movement to be sketchy to modify since if somehow you made it so that you aren't locked in the anim you would get an advantage over other players, but how can I be sure that modifying a basic run animation is safe ?

**Comment by 0ceal0t** [comment]
I guess you can't really be 100% safe, since I don't think anyone has tried to modify run or walk animations before. As long as you're replacing it with another existing run animation or doing some small modifications, it sounds to me like it should be ok, but I would advise doing a lot of testing to make sure it doesn't mess with fight mechanics, run speed, etc.

**Comment by LucyWhiteheart** [comment]
Thank you so much for all the help, I'll see on what I decide to do. This was a fun little challenge for me but I'll probably wait until someone else releases a mod like that and a good portion of people test it as safe.
