### ISSUE TITLE
How to add camera quake effect to weaponskills?

### ISSUE THREAD

**Issue by kentoadd** [0ceal0t/Dalamud-VFXEditor#24]
Hello. Title basically. I've read and followed the guide and was able to mess around enough until I managed to change "Souleater" into "Power Slash". Now I'd like to be able to add camera quake to the Power Slash, but I just can't figure out how. There's something about "Camera Quake" in effectors and the timelines, messed with those too, but I just don't know what to do to achieve the end result. Sorry if this has been covered.

**Comment by 0ceal0t** [comment]
You need to add a "camera quake" effector, and then either attach it to the timeline or an emitter (using the "Effector Select" attribute). For an example, I suggest looking at the fire 4 vfx, since I'm pretty sure that has camera shake

**Comment by kentoadd** [comment]
Alright I literally have no clue what I'm doing but finally, progress. I first tried adding my own by replicating, as best as I could, the example emitter from fire iv into the timeline on power slash right, but I wasn't able to get that to work. I've also been keeping an eye on the node graphs to make sure everything is connected but still, no good. 

Then I had the idea to export the example emitter from fire iv, and then I imported it when modifying power slash and surprisingly, it worked. In a roundabout makeshift way. It created an emitter and an effector, and all I had to do was attach the emitter to the timeline. Since making my own didn't work, I tried to use that as a template to experiment and tweak the effect, but whenever I make any changes to the effector that was created, the effects stop triggering altogether.

So If I make my own, they don't work, and If I modify the one I imported, it stops working. I'm sure the error is on my part but I'm having a hard time identifying what i'm doing wrong. I'm really grateful for the help.

If it isn't too much trouble I also have 2 additional questions.
1. how to apply the quake effects to different parts of the animation? for example, on Power slash, a quake effect on the first downward slash and the energy beam at the end. The import method i tried only adds the quake effect on the firing of the energy beam at the end, which is good, but it'd be nice if i can learn to do both.
2. how do i tweak the magnitude of the quake effect?

**Comment by 0ceal0t** [comment]
I'm not sure why it stops working when you modify the effector, that sounds really weird. If it helps, I've attached a camera shake emitter + effector which I grabbed from `Fire III#0`. You should just be able to import it and either attach the imported emitter to the timeline, or add the effector to an existing timeline.

1. Yes, you can create a "dummy" emitter which doesn't create any particles, and is associated with the effect. Then just increase the start and end time
2. The "position" and "rotation" values of the effector control the severity of the shake. Either make the peaks/valleys of the graph smaller or larger by dragging the points, and that will make it shake a different amount
[ExportedFire3CameraShake.zip](https://github.com/0ceal0t/Dalamud-VFXEditor/files/7947268/ExportedFire3CameraShake.zip)

**Comment by 0ceal0t** [comment]
Also when you say "it stops working," do you mean that it stops updating, or the camera shake doesn't happen at all?

**Comment by kentoadd** [comment]
Awesome I'll try those. Many thanks for the help.

When I said "it stops working" I meant the shakes stopped happening.  I haven't messed around with it since the last time I posted though, because I was satisfied with the results. I will definitely try to mess around with it some more now that you've showed me how to.

**Comment by moiian** [comment]
I have the same issuse.  
No any change happens after i click update. 
But the camera quake actually works after i export it and import through penumbra.
I think maybe it just can't preview.
