### ISSUE TITLE
question/possible bug

### ISSUE THREAD

**Issue by aidabun** [0ceal0t/Dalamud-VFXEditor#26]
i was trying to put the vfx from canopus lux onto sindri lux, but found that the positioning was a bit too low compared to where i wanted it. neither revised position or rotation work or do anything, while revised scale and color still reflect changes. it is a bug or is that not what those two settings are for?

**Comment by 0ceal0t** [comment]
for some visual effects, revised position and scale simply don't work. In which case, you'll have to edit the position of the emitters (`Emitters > Animations > Position`)

**Comment by 0ceal0t** [comment]
![image](https://user-images.githubusercontent.com/18051158/151283582-eb3c3e5d-ac2e-4a3f-b67a-5f77a880f1a0.png)
