### ISSUE TITLE
about actorVfxCreateAddress

### ISSUE THREAD

**Issue by tssailzz8** [0ceal0t/Dalamud-VFXEditor#27]
hello,i am a chinese plyer.i used it to do mod.i love the plugin,also i am a plugin creator，but i do not konw how to find the actorVfxCreateAddress.can you tell me how you can find them

**Comment by 0ceal0t** [comment]
Use a disassembler like Ghidra (https://ghidra-sre.org/) to find the function, then use a SigMaker plugin to find a signature for the function

![image](https://user-images.githubusercontent.com/18051158/151847359-68f62518-973f-4e29-8328-eaae737e7c16.png)
