### ISSUE TITLE
Question/ adding a very specific VFX to a skill

### ISSUE THREAD

**Issue by Nolan339** [0ceal0t/Dalamud-VFXEditor#28]
Greetings, first I'd like to thank for this plugin, it has been very useful and has helped me customize some classes to my taste. even tho I'm very new to this kind of VFX editing, and dealing with materials and etc.

That being said I've runned into a problem when I was customizing a spell.  I apologize if this question has been answered elsewhere, but Im trying my best to read the guides and other questions and I'm finding very difficult to find something that can help me. 

My goal is to transform topaz rite into thunder III. while retaining the magic circle that appears when you cast topaz rite ( Image of the circle in question: https://imgur.com/a/db4WQFz )

When I select the topaz rite VFX this is what appears: https://imgur.com/a/NElf3dK 

The first one, is the cast VFX, simple enough 

The second one vfx #0, The problem in question, is the magic circle + a small ball that goes from the caster to the target. but we will be back to it once I talk about thunder III

The third one is the hit. also very simple. 

When I inspect thunder 3, this is what appears: https://imgur.com/a/qV8hQMy

The first one, is also the cast VFX, no problem there

The second one vfx #0, is part of the problem, this is vital for the thunder animation, for it makes the thunder sphere appears and go from the caster to the target. 

the last VFX, is the hit. 

My problem is, considering that if I substitute topaz rite vfx #0 with thunder III vfx #0 I lose the magic circle, and if I don't substitute it, I don't get the animation of the thunder going from the caster to the target. What can I do and How can I do? My first thought was to add another "vfx #" since I've seen skills with more than just 2 (aside from the cast vfx) however I have no idea how do I do that. Could someone please help me? 

Thank you for your attention

**Comment by kydeixa** [comment]
Hello!

The easiest way to achieve that would be to make thunder 3 vfx#0 as the "source" file. Then go to the main timeline (there's probably just one, "Timeline 0"). You can save this timeline to your computer, in your desktop for instance. Anywhere will do.

Like so : https://imgur.com/ENttv1K
And you'll have to make sure the box is checked. This is very important: https://imgur.com/GnkEYES

Now, if you select Topaz rite vfx#0 as your new Source file, you can upload the timeline you just saved by going to the timeline tab, clicking on the "+", then import. https://imgur.com/yE2O27x

The last step to do is also simple, go to the "Scheduler" tab, add a new timeline, and replace target timeline with Timeline 1 (and make sure the "enabled" box is checked).

I think all those steps are on the wiki though, so do not hesitate to check it!

**Comment by Nolan339** [comment]
Hello thank you for your answer! It helped me a lot! Yes I tried to look for the answers on the wiki but I had a rought time understanding. But once again thank you for your help :)
