### ISSUE TITLE
TT mods crash

### ISSUE THREAD

**Issue by Kompreya** [0ceal0t/Dalamud-VFXEditor#3]
Steps taken:

I navigated to each ast card associated with the Draw ability, as follows:
vfx/common/eff/ast_card0h.avfx
vfx/common/eff/ast_card1h.avfx
vfx/common/eff/ast_card2h.avfx
vfx/common/eff/ast_card3h.avfx
vfx/common/eff/ast_card4h.avfx
vfx/common/eff/ast_card5h.avfx
vfx/common/eff/ast_card6h.avfx
vfx/common/eff/ast_card7h.avfx

I selected and replaced each texture in each avfx associated with the card texture displayed in the vfx, as follows:
ascd_s01ah.atex
ascd_s02ah.atex
ascd_s03ah.atex
ascd_s04ah.atex
ascd_s05ah.atex
ascd_s06ah.atex
ascd_s07ah.atex
ascd_s08ah.atex

These were replaced with .dds files formatted as dtx1 

I used the preview feature to verify each texture was replaced. Upon casting Draw, the vfx displayed shows the replaced texture as expected.

I selected the Save icon and selected export as a TT mod.
I then closed the game, opened TexTools, and imported the newly created mod.
Launched XIV, and cast Draw. 
Sometimes, the Draw vfx displays, but the card texture is blank (white)
Other times, the game crashes with the following error:

An unexpected error has occurred. Exiting FINAL FANTASY XIV.
2021-5-28_10:54

ffxiv_dx11.exe+ 13180A8
ffxiv_dx11.exe+ 131A69E
ffxiv_dx11.exe+ 131D165
ffxiv_dx11.exe+ 46871C
ffxiv_dx11.exe+ 197692
ffxiv_dx11.exe+ 13E6769
KERNEL32.DLL+ 17034
ntdll.dll + 52651

**Comment by 0ceal0t** [comment]
Fixed: https://github.com/0ceal0t/Dalamud-VFXEditor/commit/7766b7cebbd908feb4c3c60f3f4e64aee887aba0
