### ISSUE TITLE
Found the meaning on some values on VFX field from TMB's

### ISSUE THREAD

**Issue by Sheidyn** [0ceal0t/Dalamud-VFXEditor#30]
I was looking forward on making my own effects for my attacks, so i stumbled upon the "Unknown Pairs" on the VFX's while adding new effects to my TMB.

I am talking about these ones in particular.

![Lk483CF](https://user-images.githubusercontent.com/6161059/156026938-30006d51-9cad-4178-80fc-8f985bd61c0c.png)

I am going to assume these apply to any VFX no matter what, but i only tested with a couple of them, but i discovered the following ones:

These 3 usually default to 1:
Unknown Pairs (0,0) = Scale (X)
Unknown Pairs (0,1) = Scale (Y)
Unknown Pairs (0,2) = Scale (Z)

These 3 usually default to 0:
Unknown Pairs (1,0) = Rotation offset  (X)
Unknown Pairs (1,0) = Rotation offset  (Y)
Unknown Pairs (1,0) = Rotation offset  (Z)

These 3 usually default to 0:
Unknown Pairs (2,0) = Position offset (X)
Unknown Pairs (2,1) = Position offset (Y)
Unknown Pairs (2,2) = Position offset (Z)

These 4 usually default to 1:
Unknown Pairs (3,0) = Red color multiplier 
Unknown Pairs (3,1) = Green color multiplier 
Unknown Pairs (3,2) = Blue color multiplier
Unknown Pairs (3,3) = Opacity (0 to 1)

The rotation i am not certain if it's degrees, or it's degrees divided by a certain value. I assume it cannot be a quaternion since there's only 3 f ields.

I thought it would be useful to call these by what they mean to help people to work with TMB's, if anyone wants to experiment with them, they can at least see what these values are

I don't know if this is something that the developers already know, but since they had unknown names, i thought this could help a little bit, and suggest if possible to name them this way to help other people.

Thanks for reading!

**Comment by Mulazo77** [comment]
Very helpful! Now if only I could figure out the Bind 1-4 fields lol

**Comment by Sheidyn** [comment]
> Very helpful! Now if only I could figure out the Bind 1-4 fields lol

From a bit of testing i did yesterday, i know one of the binders, i think the first one, when set to 1 or 2 (i think?), the effect spawns on the target instead of you, i don't know about the other binders but i clearly remember changing one of the first fields back and forth and making the effect spawn in my target that i'm hitting instead of myself, hopefully that helps a bit

**Comment by 0ceal0t** [comment]
good catch on those values. I'll add them. Also pretty sure the rotation is in radians, since that's what the rest of the VFXs use

**Comment by 0ceal0t** [comment]
added in the latest update. Feel free to reopen if you find anything else
