### ISSUE TITLE
Animation start time (Question)

### ISSUE THREAD

**Issue by Mulazo77** [0ceal0t/Dalamud-VFXEditor#31]
Has anyone figured out if there is a way to set when a set animation should start from? i.e. for the shotgun (scattergun) anim, starting from the firing position instead of the reload part. Also, is there a discord set up for this plugin somewhere? Thanks!

**Comment by 0ceal0t** [comment]
If you want to adjust when a VFX is played, there's a couple of different solutions. One is to edit the .tmb file for that skill and move the VFX further back (increase the "time" attribute).

You could also change each of the items in the "timelines" tab of the VFX, and increase both their start time and end time.

For discords, you can use the [quicklauncher](https://github.com/goatcorp/FFXIVQuickLauncher#need-any-help) one

**Comment by Mulazo77** [comment]
Oh thanks but I get how to adjust the VFX, I mean strictly the animation. i.e. when you use the scattergun on MCH, it starts with the reload then shoots. I'm trying to see if there is a way to have the animation start at a later point, i.e. as soon you press the move its on the shoot part, skipping the reload. Probably not possible without editing the actual animation though, of which I have no experience.

**Comment by 0ceal0t** [comment]
ah I see. Yeah that would probably involve editing the animation using something like [AnimAssist](https://github.com/lmcintyre/AnimAssist). Other than that, try messing around with the `.tmb` file. There might be a parameter in there which corresponds to animation start frame

**Comment by Mulazo77** [comment]
Thanks! I'll keep trying to figure it out.
