### ISSUE TITLE
Question about sound replacement.

### ISSUE THREAD

**Issue by WutHavUDun** [0ceal0t/Dalamud-VFXEditor#34]
I recently discovered how to use ffxivexplorer to look for different sounds and use their filepaths to apply them to different emitters, which is really neat and useful. :) 

That being said, I do have an issue, though I understand:
 a.) ffxivexplorer hasn't been updated by its original creator in an eternity, and 
 b.) it's not your project and not your problem if it doesn't work perfectly.

Just in case you or someone else might have some insight on this anyway, I was wondering about the items in the database that haven't been updated with their proper names, (ex. something like ~12b3eb57, instead of something like se_vfx_monster_etc_shieldbash_c). Files with names resembling the former do not play when their file path is put through vfxedit. I have managed to find the names of some of the missing ones with the TMB editor (SGE and RPR ability sounds and such), but can't seem to find a way to get the other ones to work (even though I can still listen to them in ffxivexplorer).

Once again I understand this question is only tangentially related to VFXedit, but I was curious if someone else might have run into this problem, or had found some workaround.

**Comment by 0ceal0t** [comment]
The ones with names like `~12b3eb57` are files where the hash is known, but the actual file path isn't. Without finding the path, you won't be able to use them in VFXEditor. There are a couple of ways to find them.

1) The `index2` branch of FFXIVExplorer (https://github.com/goaaats/ffxiv-explorer-fork/tree/index2) has the most up-to-date `hashlist.db`. You can just download that file and replace the one in your FFXIVExplorer installation.
2) In VFXEditor, under `File > Settings`, turn on "Log all files" and then open up the log using the `/xllog` command. This will log the path of every single file that the game loads, including sound files (make sure to turn it off when you're done so you don't end up with a 10GB log file)

**Comment by WutHavUDun** [comment]
Oh wow. That updated hashlist is muuuuuch more complete than what I had. Much appreciated.

So if I'm understanding right, as long as I have the log running, I can essentially "observe" any sound in game, and use the log to find the file path?

**Comment by WutHavUDun** [comment]
After trying it out for myself. It seems that's precisely how it works.
