### ISSUE TITLE
About effects that display through other objects.

### ISSUE THREAD

**Issue by WutHavUDun** [0ceal0t/Dalamud-VFXEditor#35]
Having a bit of an issue with certain effects displaying through my character at certain depths:

![far](https://user-images.githubusercontent.com/70711148/160730919-2088c3f2-8f0a-4e63-a189-fb20b5f7ba27.png)

![mid](https://user-images.githubusercontent.com/70711148/160730921-a64d979e-d4c1-4760-875b-7c013e16515a.png)

![close](https://user-images.githubusercontent.com/70711148/160730916-990239d4-d9a0-460b-beb4-9e4c567e7ce9.png)

Are there any parameters that control this effect? I had sort of assumed it might be something in the particle settings since individual particles within the same emitter seem to show at different depths, but couldn't find anything that seemed to control it.

**Comment by 0ceal0t** [comment]
Someone else had this issue. They said
> ''Depth Offset'' in Particle Parameters seems to be responsible for transparency settings
Changing Depth Offset to 0 completely removes transparency while not altering the visual effect quality, at least on this one vfx that i tested
will need to check more vfx affected with the issue
Just tested on another VFX, my Yorha monitor had an issue where the radar line would get through the character and changing that setting to 0 fixed it as well

**Comment by 0ceal0t** [comment]
haven't tested it myself, but their solution sounds reasonable

**Comment by WutHavUDun** [comment]
Ok that was absolutely what I was looking for. (apologies for the repeat question)
