### ISSUE TITLE
Color Guide

### ISSUE THREAD

**Issue by NaesKun** [0ceal0t/Dalamud-VFXEditor#36]
Hello,

Are there any guides for color adjustment? I'm kind of lost on how to do it.

**Comment by 0ceal0t** [comment]
You can change "revised color" in the "parameters" tab or adjust the "particles > animation > color" settings. Some color settings are also handled by "Texture Color 1/2/3/4" in each particle

**Comment by NaesKun** [comment]
Perfect, thanks!
