### ISSUE TITLE
Can't update VFXs

### ISSUE THREAD

**Issue by ioverslept** [0ceal0t/Dalamud-VFXEditor#42]
I posted about this earlier, I thought it was an off bug I chanced, but it happened again. The update button doesn't update all the VFXs, only the selected one. Could this be because I have many VFXs in one workspace?

**Comment by 0ceal0t** [comment]
yes, the button only updates the currently opened VFX. if you have multiple in the same workspace, you'll have to update each individually

**Comment by ioverslept** [comment]
Weird, cause it did update all of them a few times when i opened a workspace, but after I had to do it manually. Anyway thanks for replying
