### ISSUE TITLE
Question - How to prevent VFX sharing?

### ISSUE THREAD

**Issue by MathDLW** [0ceal0t/Dalamud-VFXEditor#45]
Hello, I have a question to ask. I've been working on some overhauls for summoner at lower levels and I've stumbled into a problems. 
Emerald/topaz/ruby ruin 3(and 2) share VFX with each other. Bellow level 54 SMN also shares a VFX with SCH with Ruin 2. 

My goal is to give elemental properties to lower level summoner skills, for example using aero II VFX for Emerald Ruin 3. Using Fire 3 VFX for Ruby Ruin 3. 

Could someone help me circunvent this problem please?

**Comment by NaesKun** [comment]
Pretty sure you can't because those skills pull the VFX from the same file path. 

Unless 0ceal0t can create a logic in his editor that work similarly to metadata editing in TexTools, this is something you probably will be unable to change.
