### ISSUE TITLE
Emitter vertices not working right?

### ISSUE THREAD

**Issue by giammod** [0ceal0t/Dalamud-VFXEditor#47]
Okay, so maybe I'm missing something, I'm no expert of course, but I wanted to do something seemingly simple: change the number of stones spawned in the animation for Stone 1[ by default Stone 1 spawns 3 stones around the player and flings them at the enemy]. 

Seems like a simple idea, after looking through the Stone 1 effect, I can see Emitter3 spawns Emitter0 which spawns Particle0, Particle0 is the stone model particle. Emitter0 is set to spawn 3 particle0's at the emitter vertices of Model1[Model1 is an empty model with 3 defined emitter vertices] so far seems logical so if I wanted to add more stones to the effect(say 8 spawning around the player)

 So, I should tell Emmiter0 to spawn 8  Particle0's and add and arrange 5 more emitter vertices to Model1. Yet it doesn't work. Specifically No matter what I do it still spawns Particle0 on the 3 Emitter vertices that were originally there. it _is_ spawning 8 particles but stone 4-8 are spawning on the same 3 emitter vertices(stone 4 on vertex 0, 5 on vertex 1 and so on.) additionally if I _remove_  the emitter vertices such that there's only 1 or 2(and have the emitter set to spawn 3 or more) it still spawns them at the same three emitter vertices that were originally there. 

Am I missing a step to "codify" the emitter vertices? Does VfxEditor not work correctly with Emitter vertices? or am I missing something else entirely that's going to make me facepalm and call myself an idiot?

**Comment by 0ceal0t** [comment]
Looks like a bug. I found the issue and will have it fixed in the next update
