### ISSUE TITLE
more of a question than an issue

### ISSUE THREAD

**Issue by hikariinu124** [0ceal0t/Dalamud-VFXEditor#48]
Ive tried asking around in the xivlauncher discord for an answer for this but no one seems to know. I hope i can articulate the issue well.

I was learning to use this plugin the other day and i thought i was doing it mostly correct following the guides and video tutorials but i was trying to overwrite the Warrior actions Heavy Swing, Maim, Storms eye and Storms path with the reaper actions Slice, Waxing slice, Gibbet and Gallows respectively. I was able to get them to work sometimes, but one would always break and not work when i added the next one. I was pretty careful to follow the guide but in the event i wanted to start completely over and revert back to vanilla is there a quick and easy way to do that?

the only method i could find was disabling the plugin and restarting my game. what im looking for is an easy way to revert back to vanilla so i can fiddle with the animations and changes without having broken animations.

**Comment by 0ceal0t** [comment]
if you want to "reset" an animation (in this example, let's say _Heavy Swing_), select _Heavy Swing_ as both the loaded animation and replaced animation and click "Update". This will replace it with its original version.

**Comment by hikariinu124** [comment]
thank you so much for the reply!
