### ISSUE TITLE
Saving/Loading crashes game.

### ISSUE THREAD

**Issue by WutHavUDun** [0ceal0t/Dalamud-VFXEditor#49]
Hello,

I've been having issues today with saving/loading workspaces. I don't know if this issue is to do with me or an update, but everything was working fine when I was editing stuff a few days ago.

Like the title says, any time I try to load a workspace the game immediately crashes, and the same happens when I try to save a workspace. This happens both when I try to save over an existing workspace, and when I try to save an entirely new one. As far as I can remember I have not updated the plungin since I was working a few days ago, so I'm not sure why it would work then and not now.

If anyone else is having this issue or has any suggestions on what might be wrong, I would appreciate you letting me know. :)

Thanks

**Comment by 0ceal0t** [comment]
is there anything in your `/xllog`?

**Comment by 0ceal0t** [comment]
or `dalamud.log` in `%appdata%\XIVLauncher\`

**Comment by 0ceal0t** [comment]
did some digging, and looks like a mistake on my end. I'll have a fix out for it soon. sorry about that

**Comment by WutHavUDun** [comment]
Thank you muchly. Looking forward to it :)
