### ISSUE TITLE
about ‘undo last function’

### ISSUE THREAD

**Issue by yangjimzero** [0ceal0t/Dalamud-VFXEditor#5]
hi，I'm sorry to trouble you again.
is it easy to achieve undo function and with a hot key (ctrl+Z)?
and I also think if i can copy or paste the parameter of Emitters and particles easliy(for example, copy particle A's color including it color's keys timelime to particle B，or copy A's several  parameters to B at one time),it will be more efficient to work.
Thank you for your working of vfxeditor and your contributions！！！

**Comment by yangjimzero** [comment]
thank you for reply！Follow your own pace please~The current version is powerful enough！I really like it.i have released a few skill mods ao XMA by using your vfxeditor(called 'PAPA')!This is mainly due to you!

**Comment by 0ceal0t** [comment]
Wow, those are some extremely impressive vfxs! Keep up the great work 👍
