### ISSUE TITLE
Question about feasability of an effect

### ISSUE THREAD

**Issue by campbebj** [0ceal0t/Dalamud-VFXEditor#51]
Is there some way to put an animation on a player constantly the way spawn on self works, the best i can think of is to put it on all the body armors a player wears. but thats not quite the same, im wondering if im missing some type of VFX that could be of assistance

**Comment by 0ceal0t** [comment]
as far as I know, there's no vfx which always spawns on just the player character. You could make something like that with a dedicated plugin, but not as a simple vfx mod
