### ISSUE TITLE
Doesn't export PAP and TMB correctly in textools.

### ISSUE THREAD

**Issue by Sazuzaki** [0ceal0t/Dalamud-VFXEditor#52]
Yo.

I lost two days worth of progress in a mod due to this, but the plugin can't properly export animations to a textool mod format. For example, I'm trying to make a DRK mod utilizing the old cross class animations from Heavensward, while mixing up some of the animations. In the TMB for Straight Shot, I changed the animation cbbm_ws_h01 to cbbm_atk2. However, once I install the mod through TexTools and load it up in game, it still shows the original animation until I load it up in VFXEdit.

It's very hard to be specific about this, so let me know if I need to go in more depth. I am working with pretty obscure animations, but losing that 2 days progress is fairly annoying so I just wanted to bring this up.

**Comment by 0ceal0t** [comment]
I haven't heard of .pap or .tmb files being exported incorrectly, as there are a lot of animation mods which work fine. I can look at your case specifically if you give me the file paths you're working on. 

About losing your work, next time you should probably save your progress as a workspace (file > save), unless you're having issues with that as well
