### ISSUE TITLE
[PARSING ISSUE]

### ISSUE THREAD

**Issue by Misan404** [0ceal0t/Dalamud-VFXEditor#57]
What is the name or path of the file you are trying to open?
chara/weapon/w1501/obj/body/b0117/vfx/eff/vw0001.avfx
chara/weapon/w1501/obj/body/b0037/vfx/eff/vw0002.avfx
What type of file is it (VFX, TMB, PAP, etc.)?
VFX
![vfxerror](https://user-images.githubusercontent.com/78882965/190951757-27b671d9-383c-45f9-b7b7-004aab1a2abb.png)

**Comment by 0ceal0t** [comment]
found the issue, will be fixed in next update
