### ISSUE TITLE
[PARSING ISSUE]

### ISSUE THREAD

**Issue by w1ckr8396** [0ceal0t/Dalamud-VFXEditor#58]
What is the name or path of the file you are trying to open?: chara/equipment/e0806/vfx/eff/ve0002.avfx ([ITEM] Abyssos Cuirass of Fending #1)

What type of file is it (VFX, TMB, PAP, etc.)?: vfx

**Comment by 0ceal0t** [comment]
Will be fixed https://github.com/0ceal0t/Dalamud-VFXEditor/issues/57
