### ISSUE TITLE
about "Override Life"and"Override Life Value"

### ISSUE THREAD

**Issue by Atsarmo** [0ceal0t/Dalamud-VFXEditor#6]
hi.could you please tell me something about it?(In Emitters-Create Particles)
thank you.

**Comment by 0ceal0t** [comment]
I've never personally used those, but this is my understanding:
- Every particle and emitter has a "life" value which determines how long it is active (when it's -1, that means it's unbounded)
- When an emitter spawns another emitter or particle, the "override life" and "override life value" fields give it the option to override the new particle/emitters "life" value with something else
- This can be used, for example, if you want a particle to have a different lifespan depending on which emitter spawns it

**Comment by yangjimzero** [comment]
for example,if a Particle's life value is 100f,and the first 10f it appear(by change alpha or scale value)，and last 10f it disappear.
then you enable  "Override Life" change the "Override Life Value"in its parentEmitter,for example,change it to 50(half of it).
then the particle's life will become 50f and appear animation become first 5f,disappear animation become last 5f.

> hi.could you please tell me something about it?(In Emitters-Create Particles)
> thank you.
