### ISSUE TITLE
[Suggestion] Add a Play VFX Button

### ISSUE THREAD

**Issue by IceWolf762** [0ceal0t/Dalamud-VFXEditor#66]
Currently it is not possible to play the entire VFX for an action/spell. The only way to play the entire VFX animation is to replace the TMB with another.

As someone who RP's in XIV and relies on the VFX editor for spell animations for "added effect", it would be a great addition to add a play button to play the entire VFX without needing to replace TMB's.

If this function already exits then please let me know where it is as I can't seem to find it.

Cheers.

**Comment by 0ceal0t** [comment]
You can already spawn a VFX to preview it using the "spawn" button. Do you mean playing a `.tmb` file?

![image](https://user-images.githubusercontent.com/18051158/202801415-5badcc33-38f8-4a34-a28d-b8578c774330.png)

**Comment by IceWolf762** [comment]
Apologies for the late reply. And yes, sorry I did mean playing the `.TMB` file. Sorry for the confusion.

**Comment by 0ceal0t** [comment]
added in the last update
