### ISSUE TITLE
Changing Model Doesn't Work

### ISSUE THREAD

**Issue by AshBrighter** [0ceal0t/Dalamud-VFXEditor#7]
I've tried changing the model on a couple emotes now, but none of them seem to work. 

I might be doing something wrong, so I'm adding a clip of my attempt to this post where I try to change the big rectangle from the Eureka emote into a crumpled up version.

https://streamable.com/mpetf0

If I am doing something wrong, please let me know.

**Comment by 0ceal0t** [comment]
change "preview on" to Eureka#0 as well https://github.com/0ceal0t/Dalamud-VFXEditor/wiki/Basic-Guide#replacing-one-vfx-with-another

**Comment by AshBrighter** [comment]
Was about to slap myself for being that dumb, but it doesn't seem to have fixed the issue. 

The way I edited the model was to export the original, import it into 2.91 Blender, throw some vertices around as a test and export it as Embedded gLTF with uvs, normals, tangents, and vertex colors added. Then replace the original with the edited version.

https://streamable.com/lxnj8m

**Comment by 0ceal0t** [comment]
Oh, I see what's happening. Yeah, for now importing custom models is going to be broken. I can't say when it will be fixed, since QuickLauncher is getting a big rewrite right now in preparation for Endwalker, but I'll update this issue when it's resolved.

**Comment by 0ceal0t** [comment]
fixed in the api4 update
