### ISSUE TITLE
Question about finding a VFX/Animation Path for a buff/status effect that changes Weaponskills

### ISSUE THREAD

**Issue by kyrioA** [0ceal0t/Dalamud-VFXEditor#75]
I am trying to find the paths for Ninja's Bunshin shadow afterimages, is this possible? Searching on Actions or Status Effects seem to only point me to the VFX that give you the buff, but I'm looking for the actual VFX for the shadow clones that copy your Weaponskills. Sorry if this is the wrong place to ask.

**Comment by XCZA** [comment]
My guess is its somewhere in the 'Common' Section. a lot of extra effects on skills are there.

**Comment by kyrioA** [comment]
That's unfortunate, the Bunshin buff status effect probably isn't linked to a local visual effect that I can modify then haha. Thank you for the help, I appreciate it.
