### ISSUE TITLE
[PARSING ISSUE]

### ISSUE THREAD

**Issue by NaesKun** [0ceal0t/Dalamud-VFXEditor#86]
What is the name or path of the file you are trying to open?
vfx/action/ab_swd_abl019/eff/ab_swd019c0t.avfx

What type of file is it (VFX, TMB, PAP, etc.)?
VFX

**Comment by 0ceal0t** [comment]
Is this with version 1.7.1.8 of the plugin on an unmodded ability?

**Comment by NaesKun** [comment]
Not sure, but I can't replicate the issue anymore so I guess it's fixed with this patch.

I'll close this ticket, but can you look at my other ticket I tagged you in? Animation Cancelled by Movement. This has been plaguing a lot of the mods I've been working on as of late: https://github.com/0ceal0t/Dalamud-VFXEditor/issues/59
