### ISSUE TITLE
Question: How do you save your work with workspace??

### ISSUE THREAD

**Issue by yshtola22** [0ceal0t/Dalamud-VFXEditor#97]
I've tried doing this, and I'm not understanding something. The info on the wiki doesn't really help. How exactly am I supposed to save and continue my work from day to day?

Been at this for two days now. Lost my work on Day 1 because I didn't know how to use workspaces. Made and saved a workspace on Day 2, but it did not save any changes I had made, everything went back to default.

Am I wrong in thinking a workspace will save my current changes and reload them so I can continue? And instead I have to do a TTMP2 file after every edit, to install via TexTools and bring my stuff back into the game each time I shut it off and turn it back on?

**Comment by 0ceal0t** [comment]
Yes, workspaces are for saving your existing work. You can save it using `File > Save / Save as`, and then re-load it later using `File > Open`

Is this not working for you (is all of your work being lost, or only specific parts)? If so, can you use the `/xllog` command see if there are any errors when you are loading a workspace?

**Comment by yshtola22** [comment]
I figured it out, after some trial and error.
I have to open the Document window.
Then select my Loaded/Replaced options, so they appear in the Document window.
Then New and add Loaded/Replaced for each line, depending on how many are in the VFX I'm editing.
Then I can use File -> Save to actually save the Workspace and Document contents.
And reload the Workspace so edits I make are in the Workspace. (so Workspace shows in the main window, instead of the normal green check / Verified.

It would definitely help to have these steps in the Wiki for using Documents and Workspace.
